### ISSUE TITLE
Missing fairseq folder

### ISSUE THREAD

**Issue by KhaleelKhan** [OpenNLPLab/HGRN#1]
Hello, 

Readme mentions your version of fairseq but no link to any repository.
Can you please provide these files for training from scratch. 

Thanks.

**Comment by Doraemonzzz** [comment]
Hello, you can use the following version of fairseq:
```
https://github.com/OpenNLPLab/fairseq-evo
```
I will update the README later

**Comment by KhaleelKhan** [comment]
Thank you for the link.
