### ISSUE TITLE
Question about the experience on Imagenet1K.

### ISSUE THREAD

**Issue by jkhu29** [OpenNLPLab/HGRN#2]
Hi, thanks for your excellent work. I am concerned about the reproducibility of HGRN on image classification tasks.

In the [scripts](https://github.com/OpenNLPLab/HGRN/blob/main/train_im.sh) of Imagenet1K classification, no file is named `*.py`. What puzzles me is that no Python script appears to be executed when the experience begins. Could it be that I overlooked some other important information?

At the same time, I hope that more information about the network architecture is made available, such as how to properly use the HGRN in the DeiT/ViT. Is it intended to replace the `Self Attention layer` or the `Self Attention+FFN layers`? The article's `Transformer layers` baffled me.

Finally, as a friendly reminder, [TNN](https://github.com/OpenNLPLab/Tnn) appears to have similar issues.

---

Is [this repo](https://github.com/OpenNLPLab/im) the code base for the image classification?

**Comment by Doraemonzzz** [comment]
Thank you for the reminder. 
1. The readme here was incorrect, and I have fixed it. In fact, we use `script_im.sh`, and running this code requires the [this repo](https://github.com/OpenNLPLab/im). 
2. In Deit/ViT, the Self Attention + FFN layers are replaced with HGRU + GLU Layer. 
3. Regarding the issue with TNN, I will also upate the repo.
